### ISSUE TITLE
MacOS?

### ISSUE THREAD

**Issue by Tangston311** [drumfreak/homebridge-bluetooth-soundbutton#4]
I love the idea of this plugin, but I've got Homebridge running on a Mac.  I can get the switch to appear in my Home app, but whenever I try to activate it I get the following error relating to not finding the OMXplayer.  I know that's specific to Pi's...any way to get the sound to play via Mac you think? 

[2/17/2019, 8:07:44 AM] [SoundButton] ******* Playing Sound.... /Users/guthrieboone/SoundFiles/FireplaceOn.mp3
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/omxplayer.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Tangston311** [comment]
Update: I switched my Homebridge instance to a Pi and got this up and running just fine.
